AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile

Layout/LineLength:
  Enabled: false
